[project]
name = "subtitle-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dujx1_dell", email = "dujx1@dell.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aria2p>=0.12.1",
    "funasr",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
subtitle-download = "subtitle_download:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
